### ISSUE TITLE
Unknown error, find the error in logs.txt

### ISSUE THREAD

**Issue by l29** [redianmarku/reddit-karma-bot#1]
Hi, i just created a new Reddit account to test this script, Email verified it. Installed requirements, put my data in and run it but it gives me a error:
![image](https://user-images.githubusercontent.com/83277314/191076663-937610f4-a202-4bc6-ac2b-1e0e84a2bd95.png)

But logs.txt is empty.

**Comment by Meliz0** [comment]
I got the same error and same empty logs.txt

**Comment by Sudhanshuparihar** [comment]
> 

Even I have got the same issue

**Comment by ChristianErdtmann** [comment]
Same on my side

if i kill the executen i get error:
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\reddit-karma-bot-master\main.py", line 38, in go
    docomment()
  File "C:\Users\Administrator\Desktop\reddit-karma-bot-master\main.py", line 18, in docomment
    randomposts = open("randomposts.txt").read()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 640: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\reddit-karma-bot-master\main.py", line 61, in <module>
    go()
  File "C:\Users\Administrator\Desktop\reddit-karma-bot-master\main.py", line 52, in go
    time.sleep(60*30)
KeyboardInterrupt

If Someone find a solution please post here.

**Comment by ChristianErdtmann** [comment]
uts formatting problem you can easy fix it by use notepad++ to save the randomposts.txt formatted with utf-8 .... but you will end up in a new error...

if you want to see the errors in the log than exchange the line at: open("logs.txt", 'w').write('') ... with something that logs the error.

**Comment by ChristianErdtmann** [comment]
Here is the working code for the main.py

import slack
from datetime import datetime
import random
import os
import praw
import time
import io

sendSlackAlerts = False
mybot = praw.Reddit("bot1")
subreddit = mybot.subreddit("freekarma4u")
if not os.path.isfile("posts_replied_to.txt"):
    file = open("posts_replied_to.txt", 'w')
    file.write('')


def docomment():
    print("Bot started - Commenting every minute")
    myfile = io.open("rndposts.txt", mode="r", encoding="utf-8")
    randompostsAsString = myfile.readlines()[0]
    randomposts = randompostsAsString.split('|')
    for submission in subreddit.stream.submissions():
        done = open("posts_replied_to.txt", 'r').read().split(',')

        if submission.id not in done:
            rand = random.randint(0, len(randomposts)-1)
            randompost = randomposts[rand]
            print("Replying to post: "+submission.title)
            submission.reply(randompost)
            for i in range(80):
                time.sleep(1)
                print(i)
            with open("posts_replied_to.txt", "a") as posts_replied_to:
                posts_replied_to.write(submission.id+",")
            done = open("posts_replied_to.txt", 'r').read().split(',')


def go():
    try:
        docomment()
    except KeyboardInterrupt:
        print("\nOk stopping bot")
        exit(0)
    except Exception as error:
        if not os.path.isfile("logs.txt"):
            open("logs.txt", 'w').write(error)
        now = datetime.now()
        date = now.strftime("%m/%d/%Y %H:%M:%S")
        file = open("logs.txt", 'a')
        file.write("\n"+date)
        file.write("\n"+str(error))
        print("Unknown error, find the error in logs.txt")
        print('Waiting for 30 min')
        time.sleep(60*30)
        if sendSlackAlerts:
            slacktoken = open("slacktoken.txt").read()
            client = slack.WebClient(token=slacktoken)
            client.chat_postMessage(
                channel='alerts', text=f"An error has occured:\n{error}")
        go()


go()

**Comment by ChristianErdtmann** [comment]
but look at the code i have renamed the textfile

**Comment by Meliz0** [comment]
I got " IndentationError: unexpected indent" on Line 12

**Comment by jkgatt** [comment]
I have fixed these issues and more including Karma print in my repository: https://github.com/jkgatt/reddit-karma-bot

If @redianmarku wants to merge these into his, would be glad to contribute.

**Comment by redianmarku** [comment]
@jkgatt Create a pull request in my repository and I can check it

**Comment by jkgatt** [comment]
@redianmarku there are a number of changes described in the description: https://github.com/redianmarku/reddit-karma-bot/pull/3

Let me know if you want me to clarify anything

**Comment by jkgatt** [comment]
Thanks for merging @redianmarku! This issue can be closed off, can you confirm @v6r
